# 项目相关配置
grn:
  # 名称
  name: grn
  # 版本
  version: 1.0.0
  # 版权年份
  copyrightYear: 2025
  # 文件路径 示例（ Windows配置D:/grn/uploadPath，Linux配置 /home/grn/uploadPath）
  profile: /home/grn/uploadPath
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数字计算 char 字符验证
  captchaType: math
server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/grn_backend?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC&useSSL=false
    username: root
    password: 12345678
mybatis-plus:
  config-location:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql

